# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Using R for Quantiative Biology
description:      'Teaching the tools to get computers to do cool science'
url:              https://rfurrow.github.io/QBio/
baseurl:          /QBio
email:            refurrow@ucdavis.edu
feedbackurl:      
author:
  name:           'Rob Furrow'
  url:            

github:
  repo:           https://github.com/rfurrow/QBio
  #               Be sure the 'Issues' feature is activated in 'Settings'
